# Generated by Django 4.2.7 on 2023-12-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                ("technology_used", models.CharField(default="", max_length=50)),
                ("description", models.CharField(default="", max_length=200)),
                ("roles", models.CharField(default="", max_length=50)),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="employee_project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "e_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eid",
                        to="Employee.employee",
                    ),
                ),
                (
                    "p_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pid",
                        to="Project.project",
                    ),
                ),
            ],
            options={
                "db_table": "employee_project",
            },
        ),
    ]
