# Generated by Django 4.2.7 on 2023-12-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="codingtools",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                ("type", models.CharField(default="", max_length=50)),
            ],
            options={
                "db_table": "codingtools",
            },
        ),
        migrations.CreateModel(
            name="employee_codingtools",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Coding_tools.codingtools",
                    ),
                ),
                (
                    "eid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Employee.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_codingtools",
            },
        ),
    ]
